<?php
// auto-generated by sfPropelAdmin
// date: 2009/07/10 09:23:13
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to('list', '@list_guests?etime_id='.$guest->getEtimeId(), array (
  'class' => 'sf_admin_action_list',
)) ?></li>
  <li><?php echo submit_tag('save', array (
  'name' => 'save',
  'class' => 'sf_admin_action_save',
)) ?></li>
  <li><?php echo submit_tag('save and add', array (
  'name' => 'save_and_add',
  'class' => 'sf_admin_action_save_and_add',
)) ?></li>
</ul>
