# sfGuard
sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }
 
sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }
 
sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

# Tags
tag:
  url: /tag/:tag
  param: { module: tag, action: show }

# Outside
show_outside_event:
  url: /show/event/:slug
  param: { module: event, action: showOutside }

# Event
add_event:
  url: /event/add
  param: { module: event, action: create }

edit_event:
  url: /event/edit/:slug
  param: { module: event, action: edit }

show_event:
  url: /event/show/:slug
  param: { module: event, action: show }

list_events:
  url: /events
  param: { module: event, action: list }

# Event times
add_etime:
  url: /etime/add
  param: { module: etime, action: create }

list_times:
  url: /show_times
  param: { module: etime, action: list }

edit_etime:
  url: /etime/edit/:id
  param: { module: etime, action: edit }

# Registration form
show_reg_form:
  url: /registration_form/show/:slug
  param: { module: registration_form, action: show }

create_reg_form:
  url: /registration_form/create/:slug
  param: { module: registration_form, action: create }

change_reg_form:
  url: /registration_form/change/:slug
  param: { module: registration_form, action: change }

# Guests
list_guests:
  url: /etime/list_guests/:etime_id
  param: { module: guest, action: list }

add_guest:
  url: /etime/add_guest/:etime_id
  param: { module: guest, action: create }

add_outside_guest:
  url: /etime/online/add_guest/:etime_id
  param: { module: guest, action: createOutside }

excel:
  url: /etime/excel/:etime_id
  param: { module: guest, action: excel }

# default rules
homepage:
  url:   /
  param: { module: etime, action: list }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
