#sfGuard
sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }
 
sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }
 
sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

# Event
add_event:
  url: /add_event
  param: { module: event, action: create }

show_event:
  url: /event/:slug
  param: { module: event, action: show }

# default rules
homepage:
  url:   /
  param: { module: event, action: list }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
