default:
  http_metas:
    content-type: text/html

  metas:
    title:        Flinders University Events
    robots:       index, follow
    description:  Flinders University Events
    keywords:     Flinders University, events
    language:     en

  stylesheets:    ["http://www.flinders.edu.au/flinders/app_templates/flinderstemplates/yui/2.7.0/build/reset-fonts-grids/reset-fonts-grids.css", main, dashboard, "overcast/jquery-ui-1.7.2.custom.css"]

  javascripts:    ["jquery-ui-1.7.2.custom/js/jquery-1.3.2.min.js", "jquery-ui-1.7.2.custom/js/jquery-ui-1.7.2.custom.min.js"]

  has_layout:     on
  layout:         layout
