default:
  http_metas:
    content-type: text/html

  metas:
    title:        symfony project
    robots:       index, follow
    description:  symfony project
    keywords:     symfony, project
    language:     en

  stylesheets:    ["http://www.flinders.edu.au/flinders/app_templates/flinderstemplates/yui/2.6.0/build/reset-fonts-grids/reset-fonts-grids.css", main, dashboard]

  javascripts:    []

  has_layout:     on
  layout:         layout
