default:
  http_metas:
    content-type: text/html

  metas:
    title:        Flinders University Events
    robots:       index, follow
    description:  Flinders University Events
    keywords:     Flinders University, events
    language:     en

  stylesheets:    ["http://www.flinders.edu.au/flinders/app_templates/flinderstemplates/yui/2.6.0/build/reset-fonts-grids/reset-fonts-grids.css", main, dashboard]

  javascripts:    []

  has_layout:     on
  layout:         layout
