showOutsideSuccess:
  layout: outside_layout
publishSuccess:
  has_layout: off
createSuccess:
  stylesheets: [jquery.timeentry]
  javascripts: ["jquery-ui-1.7.2.custom/jquery.timeentry.package-1.4.5/jquery.timeentry.min.js", "etime_datetime.js"]
