prod:
  propel:
    class: sfPropelDatabase
    param:
      phptype: pgsql
      host: localhost
      database: event_calendar
      username: 'cms-apps'
      password: dark_cloud
all:
  propel:
    class: sfPropelDatabase
    param:
      phptype: pgsql
      host: localhost
      database: ems
      username: www
      password: www
