propel:
  _attributes: { noXsd: false, defaultIdMethod: none, package: lib.model }

  event:
    _attributes:        { phpName: Event, idMethod: native }
    id:                 { type: integer, required: true, primaryKey: true, autoIncrement: true }
    title:              { type: varchar(255), required: true }
    status_id:          { type: integer, foreignTable: status, foreignReference: id }
    published:          { type: boolean, required: true, default: false }
    description:        { type: longvarchar }
    notes:              { type: longvarchar }
    image_url:          { type: varchar(255) }
    organiser:          { type: longvarchar }
    interested_parties: { type: longvarchar }
    created_at:         ~

  status:
    _attributes: { phpName: Status, idMethod: native }
    id:          { type: integer, required: true, primaryKey: true, autoIncrement: true }
    status:      { type: varchar(16) }
