<?php
// auto-generated by sfPropelCrud
// date: 2009/05/27 13:35:04
?>
<h1>event</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Title</th>
  <th>Status</th>
  <th>Published</th>
  <th>Description</th>
  <th>Notes</th>
  <th>Image url</th>
  <th>Organiser</th>
  <th>Interested parties</th>
  <th>Created at</th>
</tr>
</thead>
<tbody>
<?php foreach ($events as $event): ?>
<tr>
    <td><?php echo link_to($event->getId(), 'event/show?id='.$event->getId()) ?></td>
      <td><?php echo $event->getTitle() ?></td>
      <td><?php echo $event->getStatusId() ?></td>
      <td><?php echo $event->getPublished() ?></td>
      <td><?php echo $event->getDescription() ?></td>
      <td><?php echo $event->getNotes() ?></td>
      <td><?php echo $event->getImageUrl() ?></td>
      <td><?php echo $event->getOrganiser() ?></td>
      <td><?php echo $event->getInterestedParties() ?></td>
      <td><?php echo $event->getCreatedAt() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'event/create') ?>
