<?php
// auto-generated by sfPropelCrud
// date: 2009/05/27 13:35:04
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $event->getId() ?></td>
</tr>
<tr>
<th>Title: </th>
<td><?php echo $event->getTitle() ?></td>
</tr>
<tr>
<th>Status: </th>
<td><?php echo $event->getStatusId() ?></td>
</tr>
<tr>
<th>Published: </th>
<td><?php echo $event->getPublished() ?></td>
</tr>
<tr>
<th>Description: </th>
<td><?php echo $event->getDescription() ?></td>
</tr>
<tr>
<th>Notes: </th>
<td><?php echo $event->getNotes() ?></td>
</tr>
<tr>
<th>Image url: </th>
<td><?php echo $event->getImageUrl() ?></td>
</tr>
<tr>
<th>Organiser: </th>
<td><?php echo $event->getOrganiser() ?></td>
</tr>
<tr>
<th>Interested parties: </th>
<td><?php echo $event->getInterestedParties() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $event->getCreatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'event/edit?id='.$event->getId()) ?>
&nbsp;<?php echo link_to('list', 'event/list') ?>
